$(document).ready(function(){
  $("#btn").click(function(){
    $("#tru").slideToggle(550);
  });
  $("#gal").click(function(){
    $(".test").slideToggle(1250);
  });
    setTimeout(function(){
      $("body,html").removeClass("no-scroll")
      $(".loader-ctn").fadeOut();
    },4000);
  });
  $("#gal2").click(function(){
    $(".more-graph").slideToggle();
  });